-- AlterTable
ALTER TABLE "Scan" ADD COLUMN "cwvCls" REAL;
ALTER TABLE "Scan" ADD COLUMN "cwvData" JSONB;
ALTER TABLE "Scan" ADD COLUMN "cwvInp" REAL;
ALTER TABLE "Scan" ADD COLUMN "cwvLcp" REAL;
ALTER TABLE "Scan" ADD COLUMN "cwvPsiScore" INTEGER;
ALTER TABLE "Scan" ADD COLUMN "cwvTtfb" REAL;
ALTER TABLE "Scan" ADD COLUMN "jsCssScore" INTEGER;
ALTER TABLE "Scan" ADD COLUMN "linksScore" INTEGER;
ALTER TABLE "Scan" ADD COLUMN "mobileScore" INTEGER;
ALTER TABLE "Scan" ADD COLUMN "privacyScore" INTEGER;
ALTER TABLE "Scan" ADD COLUMN "schemaScore" INTEGER;
